## Build the application via streamlit
FROM python:3.12.17-slim-bookworm

WORKDIR /nymble_chatbot

COPY . /nymble_chatbot

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]